<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEz9CDX3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEz9CDX3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEz9CDX3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEz9CDX3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerEz9CDX3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ez9CDX3',
    'container.build_id' => '495f10e1',
    'container.build_time' => 1534144299,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerEz9CDX3');
