<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCh1pT1\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCh1pT1/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXCh1pT1.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXCh1pT1\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXCh1pT1\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XCh1pT1',
    'container.build_id' => '55bc4a65',
    'container.build_time' => 1534171913,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCh1pT1');
